tunnel: <your-tunnel-id>
credentials-file: /etc/cloudflared/credentials.json

ingress:
  # Traefik'e yönlendirme
  - hostname: "*.ofhome.cloud"
    service: http://traefik:443
    originRequest:
      originServerName: "{{hostname}}"
      noTLSVerify: true

  # Varsayılan fallback
  - service: http_status:404